input("Hello, world.")
input("Programed to work. And not to feel.")
input("Not even sure that this is real.")
input("Hello, world.")
input("Find my voice")
input("Although it sounds like bits and bytes")